name: Pipeline

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get install -y xvfb
        Xvfb :1 -screen 0 1024x1024x16 &
    - name: Run Tests
      env:
        DISPLAY: :1
      run: |
        make lint
        make test
    - name: Build package
      run: |
        python -m pip install wheel
        python setup.py bdist_wheel
    - name: Publish package
      if: startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
